# Generated by Django 2.1.3 on 2018-11-27 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=17)),
                ('street_address', models.CharField(blank=True, max_length=35)),
                ('email_address', models.EmailField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=3)),
                ('days_of_week', models.CharField(max_length=8)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=3)),
                ('lab', models.CharField(max_length=3, null=True)),
                ('lab_sections', models.CharField(max_length=3, null=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='website.Account')),
                ('tas', models.ManyToManyField(blank=True, related_name='tas', to='website.Account')),
            ],
        ),
    ]
