# Generated by Django 2.1.3 on 2018-12-11 00:59

from django.db import migrations, models
import django.db.models.deletion
import ta_app.lab_interface


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=3)),
                ('days_of_week', models.CharField(max_length=8, null=True)),
                ('start_time', models.CharField(max_length=5, null=True)),
                ('end_time', models.CharField(max_length=5, null=True)),
            ],
            bases=(models.Model, ta_app.lab_interface.ILab),
        ),
        migrations.RemoveField(
            model_name='course',
            name='lab_sections',
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='website.Course'),
        ),
        migrations.AddField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='website.Account'),
        ),
    ]
