# Generated by Django 2.1.2 on 2018-12-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=3)),
                ('days_of_week', models.CharField(max_length=8)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='lab_sections',
        ),
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='website.Course'),
        ),
        migrations.AddField(
            model_name='lab',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta', to='website.Account'),
        ),
    ]
