# Generated by Django 2.1.2 on 2018-12-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181208_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='days_of_week',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='end_time',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='start_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
